// trading_journal102.jsx
// Session S95 | Monday 13 July 2026
// DIRECT WRITE CONFIRMED via filesystem MCP.

const session = {
  sessionId: "S95",
  date: "2026-07-13",
  processNotes: {
    dropboxProtocol: "DIRECT WRITE CONFIRMED via filesystem MCP.",
    ibkrConnector: "UNAVAILABLE — absent from tool registry again this session, consistent with the standing gap (10th+ consecutive session). All reconciliation performed via James's live TWS screenshots across the session, not automated pull.",
    sessionShape: "Exceptionally long, full-day session spanning pre-open reconciliation through the US close. Covered: a two-session journal gap discovered and flagged (S93/S94 had register/state activity but no journal file — this session's own new standing rule, see below, should prevent a repeat). Extensive new-thesis work on nuclear/SMR (five Stage 1s run, new standing NUCLEAR_SMR_PLAYBOOK.md file created), a live Iran-escalation-driven market selloff worked in real time (multiple stop-outs, multiple new entries, a name that broke down entirely — FAC — and a name bought on the flush and held — MRVL, later stopped — and a genuine second-attempt reclaim entered live — RKLB). Two external scout reports fact-checked and logged for tomorrow (AI-momentum StratB list, defense/infrastructure 'incorrectly sold' list). A new standing rule on weekend-vs-trading-day journal writes was codified into SESSION_CLOSE_PROTOCOL.md mid-session at James's explicit instruction.",
    newStandingRuleCodified: "Weekend/closed-market check-ins: journal write conditional on meaningful content. Active trading day closes: journal write mandatory without exception, same as every other close-step rule, regardless of session size. Written directly into SESSION_CLOSE_PROTOCOL.md this session."
  },
  ordersAndFillsThisSession: [
    { name: "KTOS", action: "NEW ENTRY, filled", detail: "Buy Limit 250sh @ $47.20 GTC, resting since morning, filled on a genuine retest after a volatile session (a $100M sole-source space-domain-awareness production award hit at the open, gapped the stock to $49.20, then flushed hard to $47.44 on real selling volume before recovering). Stop $45.00 GTC confirmed. Award independently verified against Kratos' own IR page and corroborated by Jefferies ($80 PT) and Wedbush ($85 PT, Outperform). Structural comparison run against KRMN same session: KTOS preferred on balance sheet (net cash vs KRMN's $758M debt at floating rate, doubly relevant given today's hawkish Fed-repricing backdrop), zone position, and this award demonstrating prime-contractor status versus KRMN's component-supplier role." },
    { name: "MU", action: "NEW ENTRY, filled, then STOPPED OUT same session", detail: "Fast StratB rebound, James's own framing: 'similar to MRVL,' but flagged at the time as materially thinner evidence — this was a technical/oversold read only, not independently fundamentally verified the way MRVL's dip was. Filled $932.00 (15sh) on the stated pullback-and-stabilize condition. Stop $927.29 GTC. Stopped out same session, fill $923.66. Realized loss $126.15." },
    { name: "MRVL", action: "NEW ENTRY, filled, then STOPPED OUT same session", detail: "Aggressive reclaim entry off a violent single-candle flash-crash (Iran-tension headline hit at the open, dropped the stock from $228 to sub-$217 in ~15 minutes, then showed a genuine OBV-confirmed reclaim). Filled $219.50 (100sh), better than the $220.50-221 zone proposed. Stop $217.54 GTC. Plan was to move the stop to cost ($219.50) once 'comfortably clear' — this was NOT executed before the stop fired. Stopped out fill $217.4368. Realized loss $206.32. Fundamentals independently verified pre-entry: Q1 non-GAAP EPS $0.80, record op cash flow $638.8M, raised FY27/28 guidance — the -80% GAAP 'earnings decline' that shows on a surface screen was confirmed as pure M&A purchase-accounting noise (Celestial AI/XConn), not business deterioration." },
    { name: "OKLO", action: "EXISTING POSITION, both brackets CLOSED", detail: "200sh, avg cost $49.301. Stops tightened by James mid-session from the original $44.51 (both 100sh brackets) to $45.46, deliberately ahead of a volatile session. Both brackets fired: $45.44 and $45.452. Realized loss $771.00 combined. Confirmed double-bracket structure (two separate 100sh stops, not one merged order) held correctly through the tightening and the close-out." },
    { name: "UAMY", action: "EXISTING POSITION, held", detail: "1,000sh filled @ $6.20 (StopLoss $5.60 GTC), found live at session open. Register's last verdict on this name was explicit: 'WATCHING, not actionable, pending Q2 proof of Thompson Falls ramp,' conviction only 55%. James was asked directly whether the fill was a deliberate override or an unintended autopilot fire. NOT RESOLVED this session — flag at next open, do not assume either answer." },
    { name: "RKLB", action: "NEW ENTRY, filled", detail: "Half-size starter, Buy Market 100sh @ $76.708, James's own explicit call to enter rather than wait for the $77.10 reclaim level flagged live off the chart (a genuine second bounce attempt after a first attempt had already failed at a similar level). Stop set at $65.00/$64 area — confirmed by James as deliberate, wide-berth for the long-term Neutron/Iridium thesis, to be raised once a floor becomes clear on Tuesday. REAL OPEN ITEM: the stop was submitted as DAY, not GTC, unlike every other resting stop in the book. This was flagged directly; James's response confirmed the price level as deliberate but did not explicitly confirm the DAY/GTC mechanical fix. Check this first at next open — a DAY stop expires with the session and could leave this position unprotected." },
    { name: "GTBIF", action: "EXISTING POSITION, held, STRATEGY NOTE ONLY", detail: "No trade today. James gave an explicit standing instruction this session: this is NOT viewed as a long-term hold; exit on a decent increase rather than riding it through the full DEA rescheduling process. Live stop remains $5.50 GTC, separate discretionary thesis-break trigger remains a close below $7.00-7.03. DEA hearing concludes no later than 15 July (i.e. imminent, within 1-2 sessions of this journal). D.C. Circuit stay motion: DOJ's July 2 response (opposing the stay) independently verified this session; the Circuit's actual ruling on the stay itself remains pending and unresolved." }
  ],
  closedRoundTripsThisSession: [
    { name: "OPTX", detail: "Entered S92 $8.71 (500sh). Stopped out today $8.65. Realized loss $30 (-0.7%). DISCREPANCY FLAGGED, NOT RESOLVED: documented live stop was $8.19 trigger/$7.50 limit; $8.65 is above that level. Either this was a discretionary exit or the live order differed from what was on record. James was asked directly which; not answered this session. Log as unresolved, do not assume either explanation at next open." },
    { name: "ONDS", detail: "600sh, avg cost $8.256. Stopped out today, chart-confirmed break through the documented $6.98 live stop with a real volume/OBV cascade on the final candle. NO EXPLICIT FILL PRICE WAS EVER CONFIRMED BY JAMES this session. Realized loss ESTIMATED at $765.60 using the $6.98 stop level — confirm actual fill via Trades tab at next open and correct this figure." }
  ],
  correctionsAndErrorsThisSession: [
    "Claude gave advice to pull the DAL resting order based solely on the Strategy B Iran/oil geopolitical framing, without having pulled DAL's actual documented register thesis first (a separate, unrelated Category 2 earnings/fuel-cost-mispricing setup sourced from a different scout report on 10 July). Caught and corrected in the same session once the register row was actually read — the caution on DAL was found to still be directionally right, but for a different, sharper reason (rising Iran-driven oil makes the fuel-cost thesis worse, not irrelevant to it), not the reason first given.",
    "A 'material FAC alert' James pasted, describing a 13 July Factorial/Tulip Tech partnership announcement and a specific flight-test figure, was fact-checked and found to not hold as stated — the partnership is real but dates to 21 May, and no primary source was found anywhere for the specific flight-test figure cited. Corrected before logging as a catalyst.",
    "James raised the idea of weighing alleged insider information from legacy FAC investors about Q4 developments. Declined directly and plainly — flagged this as a real legal exposure regardless of confidence in the tip, not incorporated into any thesis, sizing, or file entry.",
    "PEP: an orphaned $155.32/100-share sell order, left over from before a partial exit down to 50 shares, was flagged multiple separate times through this session and remains UNRESOLVED at close. This is a real mechanical risk (the order no longer matches the actual position size) and should be the first thing checked at next open, ahead of anything else.",
    "James set a new NNE alert at $18, which sits below the register's own already-touched $18.93 Stage 2 trigger from 12 July. Flagged that the earlier Stage 2's defined re-engage conditions (a genuine higher low, or a fresh look tied to the 13 August print) still apply regardless of the new, lower alert — the two should not be read as replacing each other."
  ],
  processImprovementsAppliedThisSession: [
    "OBV used systematically across every live chart reviewed tonight (KTOS, MRVL across three separate timeframes as a live decision was being made, RKLB across two separate live checks including catching a failed first bounce attempt before entering on the second, BWXT, ONDS, QXO) — on at least two occasions (RKLB, BWXT) this directly changed the sizing/timing recommendation given in real time rather than after the fact.",
    "Every external report reviewed tonight was fact-checked against primary sources before being trusted or logged, not assumed reliable by authorship: the Iran/StratB scout (caught one fabricated data point — a false DAL intraday high), the five-name nuclear/SMR report (confirmed AMTM/BWXT/XE/NNE/SMR core numbers, but found NNE's regulatory status was actually more advanced than stated, and surfaced a real BofA Neutral/$12 PT bear case on SMR/NuScale the original report omitted entirely), the CPIX dividend-record-date rejection logic (confirmed exactly correct), and tonight's two closing scout reports for tomorrow (StratB momentum list and the defense 'incorrectly sold' list — BWXT and EME numbers both verified in full against primary filings, high confidence; CACI/GD/GEV numbers logged but not independently re-verified, flagged as such).",
    "Created a new standing file this session, state\\NUCLEAR_SMR_PLAYBOOK.md, specifically to prevent the multi-session nuclear/SMR thesis from fragmenting across chat turns the way other threads have been lost before. Contains full Stage 1 writeups, entry zones, and open tasks; should be updated every session that touches this theme going forward, same treatment as BTC_PLAYBOOK.md.",
    "Full Stage 1s run and logged in DECISION_REGISTER.md on five nuclear/SMR names (AMTM, XE, BWXT, SMR/NuScale) plus NNE's existing Stage 1/2 cross-referenced — none taken on faith, each independently verified against primary sources before a PASS verdict was recorded.",
    "SESSION_BRIEF.md rebuilt in full this session as the actual carrier of tomorrow's plan (StratB momentum watchlist with verified entry/invalidation levels, the defense 'incorrectly sold' list, existing position decision levels for MU/MRVL/RKLB/KTOS, and the correlation warning that ALAB+MU+MRVL are one concentrated semiconductor bet, not three independent ideas) — this is the first thing that should be read at next session open."
  ],
  openItemsForNextSession: [
    "PEP orphaned $155.32/100sh sell order — highest priority mechanical fix, does not match the actual 50sh position.",
    "RKLB stop — confirm DAY vs GTC status; James confirmed the $65/$64 price level as deliberate but the order-type mechanics were not explicitly confirmed fixed.",
    "UAMY — resolve whether the live fill was James's deliberate override of the register's 'not actionable' verdict or an unintended autopilot fire.",
    "OPTX exit — resolve whether the $8.65 stop-out was discretionary or reflects a live order that differed from the documented $8.19/$7.50 stop.",
    "ONDS — confirm actual fill price via Trades tab; journal currently carries an ESTIMATED realized loss ($765.60) based on the stop level, not a confirmed fill.",
    "OKLO — full V1 refresh still not re-run this cycle (flagged originally in NUCLEAR_SMR_PLAYBOOK.md, still open).",
    "GTBIF — DEA hearing concludes no later than 15 July; James's 'exit on a decent bump, not a long-term hold' instruction is now the standing strategy for this name, watch for any bounce on hearing-related headlines given the proven sell-the-news pattern (April: spiked to $8.77, crashed to $6.57 same day).",
    "Market health regime — carried as AMBER 9/24 from S92, NOT formally recalculated this session despite a full day of real Iran-escalation and semiconductor-correction news flow. VIX itself actually fell to 15.03 (-5.11%) during today's selloff, a genuine tension with the AMBER framing worth resolving with a fresh formal read next session rather than assuming the carried figure is still accurate either direction.",
    "SESSION_BRIEF.md tomorrow's two watchlists (StratB momentum: ALAB/QTTB/FTRK/APP/MIMI/FAC/AGEN; defense 'incorrectly sold': BWXT/EME/CACI/GD/GEV) both explicitly gated on a QQQ/SMH stabilization signal before any entry — check that condition first thing before acting on either list.",
    "S93/S94 journal gap — RESOLVED, not a process failure. James confirmed post-close: weekend/no-trading sessions correctly produce no journal under the standing rule codified this session, and some days simply have no session at all (James not online). Both explain the gap. No reconstruction needed."
  ]
};

export default session;
